title = "Studying and developing nonblocking distributed MPSC queues"
institution = "Vietnam National University - Ho Chi Minh City University of Technology"
semester = 242
major = "Computer Science"
faculty = "Computer Science and Engineer"

[course]
name = "Specialized Project"
id = "CO4029"

[committee]
id = 6
secretary = "Nguyễn Phương Duy"

[[teachers]] 
name = "Thoại Nam"

[[teachers]] 
name = "Diệp Thanh Đăng"

[[students]]
name = "Đỗ Nguyễn An Huy"
id = 2110193

[fonts]
serif = ["Liberation Serif"]
monospace = ["JetBrainsMono NF", "Liberation Mono"]
