title = "Studying and developing nonblocking distributed MPSC queues"
institution = "Vietnam National University - Ho Chi Minh City University of Technology"
semester = 243
major = "Computer Science"
faculty = "Computer Science and Engineer"

[course]
name = "Capstone Project"
id = "CO4337"

[committee]
id = ""

[[teachers]] 
title = "Dr."
name = "Diệp Thanh Đăng"

[[teachers]] 
title = "Assoc. Prof. Dr."
name = "Thoại Nam"

[reviewer]
name = ""

[[students]]
name = "Đỗ Nguyễn An Huy"
id = 2110193

[fonts]
serif = ["Times Newer Roman"]
monospace = ["JetBrainsMono NF", "Liberation Mono"]
