title = ""
institution = "Vietnam National University - Ho Chi Minh City University of Technology"
semester = 242
major = "Computer Science"
faculty = "Computer Science and Engineer"

[course]
name = "Specialized Project"
id = "CO4029"

[committee]
id = 0
secretary = ""

[[teachers]] 
name = "Diệp Thanh Đăng"

[[students]]
name = ""
id = 2111762

[fonts]
serif = "Times New Roman"
monospace = "JetBrains Mono"
