title = "Studying and developing nonblocking distributed MPSC queues"
institution = "Vietnam National University - Ho Chi Minh City University of Technology"
semester = 242
major = "Computer Science"
faculty = "Computer Science and Engineer"

[course]
name = "Specialized Project"
id = "CO4029"

[committee]
id = "6 - Đồ án chuyên ngành"
secretary = "Nguyễn Phương Duy"

[[teachers]] 
title = "Dr."
name = "Diệp Thanh Đăng"

[[teachers]] 
title = "Assoc. Prof. Dr."
name = "Thoại Nam"

[[students]]
name = "Đỗ Nguyễn An Huy"
id = 2110193

[fonts]
serif = ["Times Newer Roman"]
monospace = ["JetBrainsMono NF", "Liberation Mono"]
