name: Build Typst Projects

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Typst
        uses: typst-community/setup-typst@v3
        with:
          typst-version: latest
          
      - name: Install fonts
        run: |
          sudo apt-get update
          sudo apt-get install -y fonts-liberation fonts-jetbrains-mono fonts-noto
          
      - name: Find all Typst projects
        id: find_projects
        run: |
          echo "TYPST_FILES=$(find . -name "*.typ" | grep -v "_" | grep -v "/auxiliaries/" | tr '\n' ' ')" >> $GITHUB_ENV
          mkdir -p build
      
      - name: Build PDFs from Typst files
        run: |
          for file in $TYPST_FILES; do
            filename=$(basename "$file" .typ)
            dirname=$(dirname "$file")
            echo "Building $file to build/${dirname#./}/$filename.pdf"
            mkdir -p "build/${dirname#./}"
            
            # Try to compile, continue if there's an error
            typst compile "$file" "build/${dirname#./}/$filename.pdf" || echo "Failed to build $file, continuing..."
          done
      
      - name: Generate README with links
        run: |
          echo "# Typst Project PDFs" > build/README.md
          echo "" >> build/README.md
          echo "This branch contains automatically built PDFs from Typst source files." >> build/README.md
          echo "" >> build/README.md
          echo "## Available PDFs" >> build/README.md
          echo "" >> build/README.md
          
          find build -name "*.pdf" | sort | while read pdf; do
            relative_path="${pdf#build/}"
            echo "- [$relative_path]($relative_path)" >> build/README.md
          done
          
          # Add timestamp to show when the build was last run
          echo "" >> build/README.md
          echo "Last built: $(date)" >> build/README.md
      
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
          branch: gh-pages
          clean: true
